### ISSUE TITLE
Direct Parity: Markdown support & Submission guidelines

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-payment-tool#10]
We want to eventually make the Payments app a replacement for creating challenges via Direct.
Right now the input box for "Description" is a plain text input box. I'd like to see
- add a "Submission Guidelines" input box that maps to the challenge/task's submission guidlines field
- run the input text from both the new "Submission Guidelines" field and the "Description" field through a markdown converter to produce HTML before saving.

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expanded fields](https://trello.com/c/fFzoYkJP/6-expanded-fields)

**Comment by cwdcwd** [comment]
@birdofpreyru can we get this put out to Community?

**Comment by birdofpreyru** [comment]
Ready as of a8dbf32692938b6a63a64702b826c925db13d561, and deployed to dev (https://payment.topcoder-dev.com)

**Comment by cwdcwd** [comment]
awesome job here @birdofpreyru
