### ISSUE TITLE
Unable to activate challenge in Direct bcs of Not a Number error

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/topcoder-payment-tool#13]
Received NaN error in prize amount while activating this challenge https://www.topcoder.com/direct/contest/detail.action?projectId=30067498. Please check and fix the issue.

Here is the error screenshot:

![image 7](https://user-images.githubusercontent.com/34749364/42362238-feff1788-810f-11e8-998a-c9de90f36f27.png)

**Comment by cwdcwd** [comment]
@rootelement didn't you see an error similar to this recently?

**Comment by rootelement** [comment]
This is my error.. I submitted a support ticket to get the challenge completed

**Comment by cwdcwd** [comment]
LOOOOL

**Comment by cwdcwd** [comment]
is this in Direct or in the Payment tool that this error is surfaced?

**Comment by rootelement** [comment]
I started the payment in the payment tool, which failed. I got that error when I tried to activate it in direct.

**Comment by cwdcwd** [comment]
initial failure aside, that's really a Direct error then. @JayaDhaka pls log to the appropriate repo. 

@rootelement any error message on the Payment tool you can provide?

**Comment by rootelement** [comment]
Nope, not that I saw. It just would hang on the initial "Creating Payment" then I checked the Console and saw a 504 on the API call. But I don't have it up anymore.

**Comment by JayaDhaka** [comment]
@cwdcwd I have logged this issue in Direct repo. Here is the link: https://github.com/appirio-tech/direct-app/issues/447
