### ISSUE TITLE
More Information out of Payment Tool

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-payment-tool#15]
I needed to provide data to a customer on the tasks paid out, and what I needed was member handle and dollar amount. This would be perfect in the list view on the payment tool page, but the billing account has expired as the project is done.

@cwdcwd and I discussed and he said maybe there's a possibility to surface the filters for the dropdown:
<img width="798" alt="screen shot 2018-08-06 at 4 44 13 pm" src="https://user-images.githubusercontent.com/5400156/43740019-06e39f14-9998-11e8-924e-52f4e2c93800.png">

Possibly add a switch for "Billing Account Active/Inactive" and "Project Open/Closed" Defaulting to Active and Open as it is now.

Or you could populate the list with all Billing Accounts the user has access to, but disable the " New Payment" button with a message saying the Billing Account expired.

**Comment by birdofpreyru** [comment]
Ready as of a8dbf32692938b6a63a64702b826c925db13d561, and deployed to dev (https://payment.topcoder-dev.com)
