### ISSUE TITLE
Blank page after selecting details for payments

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/topcoder-payment-tool#16]
Steps to reproduce:

Visit payment.topcoder.com
Made payment for a member on a project
If select the details, the blank(white) page will appear
@birdofpreyru
@ajefts

**Comment by NehaSharma02** [comment]
@birdofpreyru I have given you access to the project with the payment failure issue.
Project link: https://www.topcoder.com/direct/projectOverview.action?formData.projectId=18082
Project name: Mercury Prediction

**Comment by birdofpreyru** [comment]
@NehaSharma02 

Hmm... Both with prod payment tool, and when I run it locally, I see 3 payments in the project, and I can click and see details for each of them with no crush of the page. Do you still experience that problem with any of them? Is it a problem only with a freshly created challenges?

**Comment by NehaSharma02** [comment]
@birdofpreyru 

Let me check for it.
