### ISSUE TITLE
Copilot Payment

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/topcoder-payment-tool#2]
Add a way for a copilot payment to be made through the payments app so it counts toward the TCO Copilot trip.

*Moved from https://github.com/topcoder-platform/community-app/issues/831*

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Copilot add](https://trello.com/c/TSJAq4W3/9-copilot-add)

**Comment by birdofpreyru** [comment]
@narekcat 

We do not need a radio button. Payment to either member, or copilot, or to both of them from a single payment - all three options are valid. So we are fine just to have additional selector of copilot and copilot payment amount, and the logic is just: if competitor is selected and payment amount for him is set - we pay competitor, also, if copilot is selected and payment amount for him is set - we pay him as well (or only to him, if no competitor / competitor payment is set).

I think, we do not have to check whether selected copilot is really a copilot. It should be up to API to deny the payment if user selected as a copilot is not copilot, and respond with an error that we will show in the tool's UI. I am also not sure, whether we really want to restrict copilot payments only to users who have copilot role, or we want to take it easy, and allow these payments to users who are not copilots officially.

**Comment by narekcat** [comment]
@birdofpreyru 
Ok, thank you very much.

**Comment by birdofpreyru** [comment]
Ready as of a8dbf32692938b6a63a64702b826c925db13d561, and deployed to dev (https://payment.topcoder-dev.com)
