### ISSUE TITLE
Add Technologies Tags

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/topcoder-payment-tool#3]
A lot of us use the payments app now to pay out bug bash winners and stuff like that. Associating technologies with the tickets will help maintain the technologies used, so we can utilize it in the heatmap, etc.

Just include the same type-search technologies widget that's available on a challenge in direct.

*Moved from https://github.com/topcoder-platform/community-app/issues/830*

**Comment by cwdcwd** [comment]
This is a good one to include with #10

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tags](https://trello.com/c/7bOcGF3Q/7-tags)

**Comment by cwdcwd** [comment]
@birdofpreyru can we get this going w/ Community as well ?

**Comment by birdofpreyru** [comment]
@cwdcwd yeap, I missed the moment when payment tool in dev became fully functional again :) I'll move it forward now :)

**Comment by cwdcwd** [comment]
thanks @birdofpreyru !

**Comment by birdofpreyru** [comment]
Ready as of a8dbf32692938b6a63a64702b826c925db13d561, and deployed to dev (https://payment.topcoder-dev.com)
