### ISSUE TITLE
Add payment date

### ISSUE THREAD

**Issue by dustinWeaver** [topcoder-platform/topcoder-payment-tool#9]
Would be nice to see the date the payment was made.  This would assist with forensics if we think we missed a payment, etc.

**Comment by cwdcwd** [comment]
I think the payments come out in stages from PACTS and we don't have direct insight to that

**Comment by dustinWeaver** [comment]
What about just the date that it was placed in the payment tool?

**Comment by cwdcwd** [comment]
that'd be the challenge date, right? you _should_ be able to find that in Direct, for forensics, but it wouldn't be a bad addition to the UI here

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add Payment date to UI](https://trello.com/c/64I70ZRi/8-add-payment-date-to-ui)

**Comment by birdofpreyru** [comment]
Ready as of a8dbf32692938b6a63a64702b826c925db13d561, and deployed to dev (https://payment.topcoder-dev.com)

**Comment by cwdcwd** [comment]
thanks @birdofpreyru 
@dustinWeaver this has been rolled forward to production
